# Generated by Django 2.2.20 on 2022-06-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=50)),
                ('problem_desc', models.TextField()),
                ('problem_difficulty', models.CharField(choices=[('difficult', 'difficult'), ('medium', 'medium'), ('easy', 'easy')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c++', 'cpp')], max_length=10)),
                ('code_file', models.FileField(upload_to='code_file/')),
                ('verdict', models.CharField(choices=[('WA', 'Wrong Answer'), ('AC', 'All Correct'), ('TLE', 'Time Limit Exeeded'), ('MLE', 'Memory Limit Exeeded')], max_length=5)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
        ),
    ]
