# Generated by Django 2.2.20 on 2022-07-07 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=models.CharField(choices=[('PS', 'Processing'), ('WA', 'Wrong Answer'), ('AC', 'All Correct')], max_length=5),
        ),
    ]
