# Generated by Django 2.2.20 on 2022-07-07 07:09

from django.db import migrations


def populate_user(apps, schema_editor):
    Solution = apps.get_model('judge', 'Solution')
    User = apps.get_model('django.contrib.auth', 'User')
    for solution in Solution.objects.all():
        solution.user = User.objects.get(pk=1)
        solution.save()

class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20220707_1239'),
    ]

    operations = [
        migrations.RunPython(populate_user),
    ]
